### ISSUE TITLE
memfile is hashed even if hashing and signing are disabled

### ISSUE THREAD

**Issue by Kiwii** [int-72h/ofatomic#6]
`--disable-hashing` doesn't disable hashing; it just ignores a mismatch. I assume by design as the signature check also uses the new hash, but it could be skipped if signing is disabled as well.

**Comment by int-72h** [comment]
A bit of a misleading name then, I shoud call it "don't check hash"

**Comment by int-72h** [comment]
should be fixed in the next unstable commit
